### ISSUE TITLE
Frida crashes process when loading a script before resuming a spawned application

### ISSUE THREAD

**Issue by DeafBDoor** [frida/frida-java#26]
Frida version 9.1.23, with both frida-server-9.1.23-android-arm64 and frida-server-9.1.23-android-x86_64 (both on a rooted Galaxy S7 phone and the latest Android N emulator from Google)

Used the following command sequence (with associated output):
$ frida -U -f sg.vantagepoint.uncrackable1
Waiting for USB device to appear...
Spawned `sg.vantagepoint.uncrackable1`. Use %resume to let the main thread start executing!
[USB::Samsung SM-G930F::['sg.vantagepoint.uncrackable1']]-> %load uncrackable_access.js
[USB::Samsung SM-G930F::['sg.vantagepoint.uncrackable1']]-> %resume
[USB::Samsung SM-G930F::['sg.vantagepoint.uncrackable1']]-> Error: access violation accessing 0xebad8082
    at Env.<anonymous> (frida/node_modules/frida-java/lib/env.js:206:1)
    at ClassFactory.use (frida/node_modules/frida-java/lib/class-factory.js:113:1)
    at ActivityThread.fromJni (frida/node_modules/frida-java/lib/class-factory.js:1624:1)
    at ActivityThread.getPackageInfoNoCheck (eval at makeMethod (frida/node_modules/frida-java/lib/class-factory.js:1015:1))
    at ActivityThread.m.implementation (frida/node_modules/frida-java/index.js:302:1)
    at getPackageInfoNoCheck (eval at implement (frida/node_modules/frida-java/lib/class-factory.js:1370:1), <anonymous>:1:)
[USB::Samsung SM-G930F::['sg.vantagepoint.uncrackable1']]-> 
[USB::Samsung SM-G930F::['sg.vantagepoint.uncrackable1']]-> Process terminated

```javascript
File uncrackable_access.js contains the following script:
Java.perform(function() { 
        var bclass = Java.use("sg.vantagepoint.uncrackable1.b");
        bclass.onClick.implementation = function(a,b) {
        console.log("Intercepted onClick");
    }
});
```

App sg.vantagepoint.uncrackable1 can be downloaded here: https://github.com/OWASP/owasp-mstg/blob/master/OMTG-Files/02_Crackmes/01_Android/Level_01/UnCrackable-Level1.apk

**Comment by enovella** [comment]
What a coincidence! Take a peek at #29 to see if it helps

**Comment by oleavr** [comment]
Same as #29, let's keep tracking it there since it has more details.
