### ISSUE TITLE
Java.enumerateLoadedClasses() throws an error (access violation)

### ISSUE THREAD

**Issue by oleavr** [frida/frida-java#7]
(Continuation of frida/frida-node#22.)

As described by @TelmoNeves:

While trying to use Java.enumerateLoadedClasses I get the following error:

{ type: 'error',
  description: 'Error: access violation accessing 0x0',
  stack: 'Error: access violation accessing 0x0\n    at _enumerateLoadedClasses (frida/node_modules/frida-java/index.js:98:30)\n    at Runtime.value [as enumerateLoadedClasses] (frida/node_modules/frida-java/index.js:145:7)\n    at agent.js:446:8\n    at VM.perform (frida/node_modules/frid
a-java/lib/vm.js:35:7)\n    at performPending (frida/node_modules/frida-java/index.js:221:14)\n    at frida/node_modules/frida-java/index.js:196:15\n    at VM.perform (frida/node_modules/frida-java/lib/vm.js:35:7)\n    at Runtime.perform (frida/node_modules/frida-java/index.js:191:14)\n    at Object
.1 (agent.js:5:7)\n    at s (node_modules/frida-load/node_modules/browserify/node_modules/browser-pack/_prelude.js:1:1)',
  fileName: 'frida/node_modules/frida-java/index.js',
  lineNumber: 98,
  columnNumber: 30 }

I remember using this function at the beginning of the year and it worked.

My device is a Samsung Note 3 rooted running android 4.3

I also tested with an emulator and I got the same error.

**Comment by oleavr** [comment]
Fixed in latest versions.
