### ISSUE TITLE
.Error: invalid instruction

### ISSUE THREAD

**Issue by muhzii** [frida/frida-java#86]
This issue is moved from: [Error: invalid instruction with Java.choose()](https://github.com/frida/frida/issues/566)

As it happens, frida fails while I try to inspect instances with `Java.choose`.

**Device info:**

Architecture: arm
ABI: armeabi-v7a
Android version: 5.0
API level: 21

However, I run the test suite on the device and this is what I get:

```
JUnit version 4.12
.Error: invalid instruction
    at Object.value (frida/runtime/core.js:553:1)
    at _loop2 (../lib/android.js:1021:16)
    at recompileExceptionClearForArm (../lib/android.js:995:30)
    at ../lib/android.js:809:15
    at Object.value [as patchCode] (frida/runtime/core.js:257:1)
    at _getArtThreadStateTransitionImpl (../lib/android.js:808:3)
    at ../lib/android.js:1441:7
    at withRunnableArtThread (../lib/android.js:641:19)
    at enumerateLoadedClassesArt (../index.js:178:5)
    at Runtime.value [as enumerateLoadedClasses] (../index.js:118:9)
E.Error: invalid instruction
    at Object.value (frida/runtime/core.js:553:1)
    at _loop2 (../lib/android.js:1021:16)
    at recompileExceptionClearForArm (../lib/android.js:995:30)
    at ../lib/android.js:809:15
    at Object.value [as patchCode] (frida/runtime/core.js:257:1)
    at _getArtThreadStateTransitionImpl (../lib/android.js:808:3)
    at ../lib/android.js:1441:7
    at withRunnableArtThread (../lib/android.js:641:19)
    at ClassFactory.choose (../lib/class-factory.js:247:7)
    at Runtime.choose (../index.js:380:5)
E.......................
Time: 27.195
There were 2 failures:
1) loadedClassesCanBeEnumerated(re.frida.ClassRegistryTest)
java.lang.AssertionError: expected:<found=true> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at re.frida.ClassRegistryTest.loadedClassesCanBeEnumerated(ClassRegistryTest.java:24)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
	at re.frida.TestRunner.main(TestRunner.java:23)
2) liveObjectsCanBeEnumerated(re.frida.ClassRegistryTest)
java.lang.AssertionError: expected:<count=1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at re.frida.ClassRegistryTest.liveObjectsCanBeEnumerated(ClassRegistryTest.java:62)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
	at re.frida.TestRunner.main(TestRunner.java:23)

FAILURES!!!
Tests run: 25,  Failures: 2
```

**Comment by oleavr** [comment]
This was fixed in 0a1ea87f72e5125bff64023ed378ce2748d62271.
